In [ ]:
# Part 1: Handle Missing Values & Duplicates

    # Step-by-Step Guidelines:
# 1. Load the Data: First, ensure you have pandas installed and import it.
# 2. Handling Missing Values
#     1. Identify Missing Values:
#     2. Fill Missing Values:
# 3. Handling Duplicates
#     1. Identify Duplicates:
#     2. Remove Duplicates:
# 4. Combined Practice on a New Dataset
#     1. New Sample Data:
#     2. Handling Missing Values:
#     3. Remove Duplicates:

In [ ]:
# Part 2: Apply Standardization & Formatting Rules

#     Step-by-Step Guidelines:
# 1. Standardize Text Data
#     1. Convert All Names to Lowercase:
# 2. Format Numerical Data
#     1. Round Age Column to the Nearest Integer:
# 3. Combined Practice on Another Dataset
#     1. New Sample Data:
#     2. Standardize Product Names:
#     3. Format Prices to Two Decimal Places:

In [1]:
import pandas as pd
import numpy as np

# ----------------------------
# Part 1: Handle Missing Values & Duplicates
# ----------------------------

# 1. Load Data (using a sample dataset here)
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', None, 'Eve', 'Frank', 'Bob'],
    'Age': [25, np.nan, 30, 25, 40, np.nan, 35, np.nan],
    'Email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 'alice@example.com', None, 'eve@example.com', 'frank@example.com', 'bob@example.com']
}

df = pd.DataFrame(data)
print("Original Data:")
print(df)

# 2. Handling Missing Values

# 2.1 Identify Missing Values
print("\nMissing values per column:")
print(df.isnull().sum())

# 2.2 Fill Missing Values
# Fill missing 'Age' with median age
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

# Fill missing 'Name' with placeholder 'Unknown'
df['Name'] = df['Name'].fillna('Unknown')

# 3. Handling Duplicates

# 3.1 Identify Duplicates
duplicates = df.duplicated()
print("\nDuplicate rows:")
print(df[duplicates])

# 3.2 Remove Duplicates
df = df.drop_duplicates()
print("\nData after removing duplicates:")
print(df)

# ----------------------------
# Part 2: Apply Standardization & Formatting Rules
# ----------------------------

# 1. Standardize Text Data

# 1.1 Convert all 'Name' values to lowercase
df['Name'] = df['Name'].str.lower()

# 2. Format Numerical Data

# 2.1 Round 'Age' to nearest integer
df['Age'] = df['Age'].round().astype(int)

print("\nData after standardizing text and formatting numbers:")
print(df)

# 3. Combined Practice on Another Dataset

# 3.1 New Sample Dataset for products
product_data = {
    'Product': ['Laptop', 'SmartPhone', 'HeadPhones', 'Laptop', 'smartphone'],
    'Price': [999.999, 499.499, 79.995, 999.999, 499.499]
}

product_df = pd.DataFrame(product_data)
print("\nOriginal Product Data:")
print(product_df)

# 3.2 Standardize Product Names (lowercase)
product_df['Product'] = product_df['Product'].str.lower()

# 3.3 Format Prices to 2 decimal places
product_df['Price'] = product_df['Price'].round(2)

print("\nProduct Data after standardization and formatting:")
print(product_df)

Original Data:
      Name   Age                Email
0    Alice  25.0    alice@example.com
1      Bob   NaN      bob@example.com
2  Charlie  30.0  charlie@example.com
3    Alice  25.0    alice@example.com
4     None  40.0                 None
5      Eve   NaN      eve@example.com
6    Frank  35.0    frank@example.com
7      Bob   NaN      bob@example.com

Missing values per column:
Name     1
Age      3
Email    1
dtype: int64

Duplicate rows:
    Name   Age              Email
3  Alice  25.0  alice@example.com
7    Bob  30.0    bob@example.com

Data after removing duplicates:
      Name   Age                Email
0    Alice  25.0    alice@example.com
1      Bob  30.0      bob@example.com
2  Charlie  30.0  charlie@example.com
4  Unknown  40.0                 None
5      Eve  30.0      eve@example.com
6    Frank  35.0    frank@example.com

Data after standardizing text and formatting numbers:
      Name  Age                Email
0    alice   25    alice@example.com
1      bob   30      bob@example.com
2  charlie   30  charlie@example.com
4  unknown   40                 None
5      eve   30      eve@example.com
6    frank   35    frank@example.com

Original Product Data:
      Product    Price
0      Laptop  999.999
1  SmartPhone  499.499
2  HeadPhones   79.995
3      Laptop  999.999
4  smartphone  499.499

Product Data after standardization and formatting:
      Product   Price
0      laptop  1000.0
1  smartphone   499.5
2  headphones    80.0
3      laptop  1000.0
4  smartphone   499.5